from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'koaliapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/','up.views.register'),
    url(r'^verify_mail/','up.views.verify_mail'),
    url(r'^verify_phone/','up.views.verify_phone'),
    url(r'^activate/','up.views.activate'),
    url(r'^summit_verifying_code/','up.views.summit_verifying_code'),
    url(r'^find_phone/','up.views.find_phone'),
    url(r'^find_password/','up.views.find_password'),
    url(r'^check/','up.views.check'),
    url(r'^login/','up.views.login'),
    url(r'^upload/','up.views.uploadImg'),
    url(r'^getBaseInfo/','up.mainpages.getBaseInfo'),
    url(r'^changeBaseInfo','up.mainpages.changeBaseInfo'),
    url(r'^getTag/','up.planviews.getTag'),
    url(r'^changeTag/','up.planviews.changeTag'),
    url(r'^getPlan/','up.planviews.getPlan'),
    url(r'^getProvinceList/','up.mainpages.getProvinceList'),
    url(r'^getCityList/','up.mainpages.getCityList'),
    url(r'^getSchoolList/','up.mainpages.getSchoolList'),
 #   url(r'^getMajorClassfied/','up.mainpages.getMajorClassfiedList'),
    url(r'^getConnectInfo/','up.mainpages.getConnectInfo'),
    url(r'changeConnectInfo','up.mainpages.changeConnectInfo'),
    url(r'^changePlan/','up.planviews.changePlan'),
    url(r'^addMember/','up.planviews.addMember'),
    url(r'^deleteMember/','up.planviews.deleteMember'),
    url(r'^addResume/','up.planviews.addResume'),
    url(r'^deleteResume/','up.planviews.deleteResume'),
    url(r'^checkResume/','up.planviews.checkResume'),
    url(r'^updateResume/','up.planviews.updateResume'),
    url(r'^uploadCashflow/','up.planviews.uploadCashflow'),
    url(r'^uploadProfitAndLoss/','up.planviews.uploadProfitAndLoss'),
    url(r'^uploadOpportunitiesAndRisks/','up.planviews.uploadOpportunitiesAndRisks'),
    url(r'^search/','up.mainpages.search'),
    url(r'^userView/','up.mainpages.userView'),
    url(r'^shift_visuality/','up.planviews.shift_visuality'),
    url(r'^poineeringCircle/','up.mainpages.poineeringCircle'),
    url(r'^investingCircle/','up.mainpages.investingCircle'),
    url(r'^industryList/','up.mainpages.industryList'),
    url(r'^projectInfo/','up.mainpages.projectInfo'),
    url(r'^investInfo/','up.mainpages.investInfo'),
    url(r'^feedback/','up.views.feedback'),
    url(r'^$', 'up.webpages.official_page'),
    url(r'^register_phone/','up.webpages.register_phone'),
    url(r'^register_mail/','up.webpages.register_mail'),
    url(r'^protocol/','up.webpages.protocol'),
    url(r'^success/','up.webpages.success'),
    url(r'^web_login/','up.webpages.web_login'),
    url(r'^login_verify/','up.webpages.login'),
    url(r'^web_changePlan/','up.webpages.changePlanview'),
    url(r'^web_changeTag/','up.webpages.changeTag'),
    url(r'^web_changeInvestInfo/','up.webpages.changeInvestTag'),
    url(r'^web_shift/','up.webpages.shift_visuality'),
    url(r'^mainpage/','up.webpages.mainpage'),
    url(r'^web_upload/','up.webpages.uploadImg'),
    url(r'^web_poineeringCircle/','up.webpages.poineeringCircle'),
    url(r'^web_poineeringInfo/','up.webpages.poineeringInfo'),
    url(r'^web_investmentCircle/','up.webpages.investmentCircle'),
    url(r'^web_investmentInfo/','up.webpages.investInfo'),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
)
